# Generated by Django 5.2 on 2025-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g. '2 hours', '4-6 hours'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='materials',
            field=models.TextField(blank=True, help_text='Materials and equipment to be used', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='staff_count',
            field=models.IntegerField(default=1, help_text='Expected number of staff'),
        ),
    ]
