# Generated by Django 5.2 on 2025-05-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_duration_service_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
