# Generated by Django 5.2.1 on 2025-06-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/after/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='before_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/before/'),
        ),
    ]
