# Generated by Django 5.2.1 on 2025-06-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_after_photo_booking_before_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='after_photo',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='before_photo',
        ),
    ]
