# Generated by Django 5.2.1 on 2025-06-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_municipality_province_barangay_municipality_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='province',
        ),
        migrations.DeleteModel(
            name='Barangay',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
