# Generated by Django 5.2 on 2025-08-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_municipality_province_delete_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_note',
            field=models.TextField(blank=True, help_text="Admin's note about service requirements (e.g., 'We will use your water supply and electricity')", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_note',
            field=models.TextField(blank=True, help_text="Customer's note for the service (e.g., 'May aso dito')", null=True),
        ),
    ]
