# Generated by Django 5.2 on 2025-08-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='downpayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='40% downpayment amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_downpayment_confirmed',
            field=models.BooleanField(default=False, help_text='Whether admin has verified the downpayment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used (GCash, PayMaya, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Payment reference number from GCash, PayMaya, etc.', max_length=100, null=True),
        ),
    ]
