# Generated by Django 5.2 on 2025-08-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking_downpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='after_photo',
            field=models.ImageField(blank=True, help_text='Photo taken after service completion', null=True, upload_to='photos/after/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='before_photo',
            field=models.ImageField(blank=True, help_text='Photo taken before service starts', null=True, upload_to='photos/before/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_full_payment_confirmed',
            field=models.BooleanField(default=False, help_text='Whether full payment has been confirmed by staff'),
        ),
    ]
